# JSON Merge Patch to fix bugs from the keycloak-openapi scrapper/generator.

AbstractAuthenticationExecutionRepresentation: null
AbstractPolicyRepresentation: null

ClientPoliciesRepresentation:
  properties:
    policies:
      # https://github.com/dahag-ag/keycloak-openapi/issues/7
      items:
        type: null
        description: null
        $ref: "#/$defs/ClientPolicyRepresentation"

# https://github.com/dahag-ag/keycloak-openapi/issues/7
ClientPolicyRepresentation:
  type: object
  additionalProperties: false
  properties:
    name:
      type: string
    description:
      type: string
    enabled:
      type: boolean
    conditions:
      type: array
      items:
        $ref: "#/$defs/ClientPolicyConditionRepresentation"
    profiles:
      type: array
      items:
        type: string

ComponentExportRepresentation:
  properties:
    config:
      # https://github.com/dahag-ag/keycloak-openapi/issues/5 (still wrong in <22.0.1)
      additionalProperties:
        type: array
        items:
          type: string
    subComponents:
      # https://github.com/dahag-ag/keycloak-openapi/issues/5 (still wrong in <22.0.1)
      additionalProperties:
        $ref: null
        type: array
        items:
          $ref: "#/$defs/ComponentExportRepresentation"

ComponentRepresentation:
  properties:
    config:
      # https://github.com/dahag-ag/keycloak-openapi/issues/5 (still wrong in <22.0.1)
      additionalProperties:
        type: array
        items:
          type: string

CredentialRepresentation:
  properties:
    config:
      # https://github.com/dahag-ag/keycloak-openapi/issues/5 (still wrong in <22.0.1)
      additionalProperties:
        type: array
        items:
          type: string

RealmRepresentation:
  properties:
    # https://github.com/dahag-ag/keycloak-openapi/issues/7
    oAuth2DeviceCodeLifespan: null
    oauth2DeviceCodeLifespan:
      type: integer
      format: int32
      minimum: -2147483648
      maximum: 2147483647
    # https://github.com/dahag-ag/keycloak-openapi/issues/7
    oAuth2DevicePollingInterval: null
    oauth2DevicePollingInterval:
      type: integer
      format: int32
      minimum: -2147483648
      maximum: 2147483647
    # https://github.com/dahag-ag/keycloak-openapi/issues/7
    clientPolicies:
      $ref: "#/$defs/ClientPoliciesRepresentation"
    # https://github.com/dahag-ag/keycloak-openapi/issues/7
    clientProfiles:
      $ref: "#/$defs/ClientProfilesRepresentation"
    components:
      # https://github.com/dahag-ag/keycloak-openapi/issues/5 (still wrong in <22.0.1)
      additionalProperties:
        $ref: null
        type: array
        items:
          $ref: "#/$defs/ComponentExportRepresentation"
