name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout dahag-ag/keycloak-openapi
        uses: actions/checkout@v3
        with:
          repository: dahag-ag/keycloak-openapi
          path: keycloak-openapi

      - name: Install npm dependencies
        run: npm ci

      - name: Convert OpenAPI definitions to JSON schemas
        run: |
          srcdir=keycloak-openapi/OpenApiDefinitions
          mkdir -p public

          for ver in 17.0.1 18.0.0 19.0.0 20.0.0; do
              ./bin/convert $srcdir/keycloak-$ver.json patches/*.yml > public/keycloak-$ver.json
              ./bin/convert --only-realm-export $srcdir/keycloak-$ver.json patches/*.yml > public/keycloak-realm-$ver.json
          done

          ./bin/convert $srcdir/keycloak-21.0.0.json patches/*.yml patches/v21+/*.yml \
              > public/keycloak-21.0.0.json
          ./bin/convert --only-realm-export $srcdir/keycloak-21.0.0.json patches/*.yml patches/v21+/*.yml \
              > public/keycloak-realm-21.0.0.json

          ./bin/convert $srcdir/keycloak-22.0.1.json patches/*.yml patches/v21+/*.yml patches/v22/*.yml \
              > public/keycloak-22.0.1.json
          ./bin/convert --only-realm-export $srcdir/keycloak-22.0.1.json patches/*.yml patches/v21+/*.yml patches/v22/*.yml \
              > public/keycloak-realm-22.0.1.json

      - name: Validate JSON schemas
        run: ./node_modules/.bin/ajv validate --strict=true -s meta-schema.json -d 'public/*.json'

      - name: Generate directory listings
        uses: jayanta525/github-pages-directory-listing@20409ce0808d816bcbc3090ed7a6a784cf6ed9df
        with:
          FOLDER: public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    needs: build
    permissions:
      pages: write  # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
