name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm ci

      - name: Convert OpenAPI definitions to JSON schemas
        run: |
          mkdir -p schemas

          for ver in 24.0.5 25.0.6; do
            ./bin/convert openapi/keycloak-$ver.json patches/v24+/*.yml patches/v${ver%%.*}/*.yml \
                > schemas/keycloak-all-$ver.json
            ./bin/convert --only-realm-export openapi/keycloak-$ver.json patches/v24+/*.yml patches/v${ver%%.*}/*.yml \
                > schemas/keycloak-realm-$ver.json
          done

          for ver in 26.0.2 26.1.1; do
            ./bin/convert openapi/keycloak-$ver.json patches/v24+/*.yml patches/v26+/*.yml patches/v${ver%%.*}/*.yml \
                > schemas/keycloak-all-$ver.json
            ./bin/convert --only-realm-export openapi/keycloak-$ver.json patches/v24+/*.yml patches/v26+/*.yml patches/v${ver%%.*}/*.yml \
                > schemas/keycloak-realm-$ver.json
          done

      - name: Validate JSON schemas
        run: ./node_modules/.bin/ajv validate --strict=true -s meta-schema.json -d 'schemas/*.json'

      - name: Duplicate schemas without minor and patch version
        run: |
          for filename in *.json; do
            cp "$filename" "${filename%%.*}.json"
          done
        working-directory: schemas

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: schemas
          path: ./schemas

  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download and unpack artifact
        uses: actions/download-artifact@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy generated files to gh-pages
        run: cp schemas/* gh-pages/

      - name: Check if there are any changes
        id: has_changes
        working-directory: gh-pages
        run: |
          git status || exit 1
          test -n "$(git status --porcelain)" && result=yes || result=no
          echo "result=$result" >> "$GITHUB_OUTPUT"

      - name: Remove existing index.html
        if: steps.has_changes.outputs.result == 'yes'
        run: rm -f index.html
        working-directory: gh-pages

      - name: Generate directory listings
        if: steps.has_changes.outputs.result == 'yes'
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: gh-pages

      - name: Commit changes
        if: steps.has_changes.outputs.result == 'yes'
        working-directory: gh-pages
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Built from ${{ github.sha }}"

      - name: Push changes back to origin
        if: steps.has_changes.outputs.result == 'yes'
        working-directory: gh-pages
        run: |
          # XXX: workaround for https://github.com/orgs/community/discussions/55820
          git config --global http.version HTTP/1.1
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages
